-- ❌ LEGACY MIGRATION – NICHT MEHR VERWENDEN
-- =====================================================================
-- Name: 016_add_essence_to_readings.sql
-- Status: DEAKTIVIERT / HISTORISCH
--
-- Diese Migration gehört zu einem veralteten Reading-System (V1),
-- das auf der Tabelle `readings` basierte.
--
-- ❗ WICHTIG:
-- - Die Tabelle `readings` existiert NICHT mehr.
-- - Das aktive System verwendet `coach_readings` (V2).
-- - Essence wird NICHT mehr als eigene Spalte gespeichert,
--   sondern ist Bestandteil der generierten Reading-Versionen.
--
-- Diese Datei darf NICHT ausgeführt werden.
-- Sie dient ausschließlich der historischen Nachvollziehbarkeit.
--
-- =====================================================================
-- AKTUELLES SYSTEM (V2)
-- =====================================================================
-- ✔ Tabelle: coach_readings
-- ✔ Reading-Versionen: readings_v2_json / Versionssystem
-- ✔ Essence: Bestandteil des generierten Inhalts (nicht separat persistiert)
-- ✔ Jobs & Status: reading_jobs
--
-- Siehe:
-- - SYSTEM-STATUS.md
-- - MIGRATION-QUICK-START.md
--
-- =====================================================================
-- AUSFÜHRUNG:
-- ❌ NICHT AUSFÜHREN
-- ❌ NICHT REAKTIVIEREN
-- ❌ NICHT ANPASSEN
-- =====================================================================

-- intentionally left blank

