#!/bin/bash
# A4 – Manuelle Deployment-Schritte
# Führe diese Befehle Schritt für Schritt auf den Servern aus

set -e

echo "🔥 A4 – System-Konsolidierung: Manuelle Deployment-Schritte"
echo "============================================================"
echo ""
echo "⚠️  WICHTIG: Führe diese Befehle auf den jeweiligen Servern aus!"
echo ""

# ============================================
# HETZNER SERVER (138.199.237.34)
# ============================================
echo "📦 HETZNER SERVER (138.199.237.34)"
echo "=================================="
echo ""
echo "1️⃣  SSH zum Hetzner Server:"
echo "   ssh root@138.199.237.34"
echo ""
echo "2️⃣  Git Pull:"
echo "   cd /opt/mcp-connection-key"
echo "   git pull origin feature/reading-agent-option-a-complete"
echo ""
echo "3️⃣  chatgpt-agent Container stoppen & entfernen:"
echo "   docker stop chatgpt-agent || true"
echo "   docker rm chatgpt-agent || true"
echo "   docker ps -a | grep chatgpt-agent"
echo "   # Erwartung: Keine Ausgabe"
echo ""
echo "4️⃣  Docker Compose neu laden:"
echo "   cd /opt/mcp-connection-key"
echo "   docker compose up -d --remove-orphans"
echo ""
echo "5️⃣  Docker Status prüfen:"
echo "   docker compose ps"
echo "   # Erwartung: KEIN chatgpt-agent mehr sichtbar"
echo ""
echo "6️⃣  PM2 Reading-Agent starten/restarten:"
echo "   cd /opt/mcp-connection-key/production"
echo "   pm2 restart reading-agent --update-env || pm2 start server.js --name reading-agent"
echo "   pm2 save"
echo ""
echo "7️⃣  PM2 Status prüfen:"
echo "   pm2 status"
echo "   # Erwartung: reading-agent läuft"
echo ""
echo "8️⃣  Port 4000 verifizieren:"
echo "   lsof -i :4000"
echo "   # ODER: netstat -tuln | grep 4000"
echo "   # ODER: ss -tuln | grep 4000"
echo "   # Erwartung: Node/PM2 Prozess, KEIN Docker"
echo ""
echo "9️⃣  Health Check:"
echo "   curl http://localhost:4000/health"
echo "   # Erwartung: {\"status\":\"ok\",\"service\":\"reading-agent\",...}"
echo ""
echo ""

# ============================================
# CK-APP SERVER (167.235.224.149)
# ============================================
echo "📦 CK-APP SERVER (167.235.224.149)"
echo "=================================="
echo ""
echo "1️⃣  SSH zum CK-App Server:"
echo "   ssh root@167.235.224.149"
echo ""
echo "2️⃣  Git Pull (falls Git-Repository vorhanden):"
echo "   cd /opt/hd-app/The-Connection-Key/frontend"
echo "   git status"
echo "   # Falls Git-Repository vorhanden:"
echo "   git pull origin feature/reading-agent-option-a-complete"
echo ""
echo "2️⃣  ODER: Dateien manuell kopieren (falls kein Git):"
echo "   # Auf lokalem Rechner (PowerShell):"
echo "   scp integration/api-routes/readings-generate.ts root@167.235.224.149:/opt/hd-app/The-Connection-Key/frontend/app/api/readings/generate.ts"
echo ""
echo "3️⃣  Frontend Container neu bauen:"
echo "   cd /opt/hd-app/The-Connection-Key"
echo "   docker compose stop frontend"
echo "   docker compose build --no-cache frontend"
echo "   docker compose up -d frontend"
echo ""
echo "4️⃣  Container Status prüfen:"
echo "   docker compose ps frontend"
echo "   # Erwartung: frontend läuft"
echo ""
echo "5️⃣  Logs prüfen:"
echo "   docker compose logs frontend --tail 50"
echo "   # Erwartung: Keine Build-Fehler"
echo ""
echo ""

# ============================================
# SUPABASE MIGRATION
# ============================================
echo "📦 SUPABASE MIGRATION"
echo "====================="
echo ""
echo "1️⃣  Im Supabase Dashboard:"
echo "   - SQL Editor öffnen"
echo "   - Datei: integration/supabase/migrations/019_add_agent_metadata_to_readings.sql"
echo "   - SQL ausführen"
echo ""
echo "2️⃣  Prüfen:"
echo "   SELECT column_name FROM information_schema.columns WHERE table_name = 'readings' AND column_name IN ('agent_id', 'agent_version', 'prompt_hash');"
echo "   # Erwartung: 3 Zeilen (agent_id, agent_version, prompt_hash)"
echo ""
echo ""

# ============================================
# FINALE VERIFIZIERUNG
# ============================================
echo "✅ FINALE VERIFIZIERUNG"
echo "======================="
echo ""
echo "Hetzner Server:"
echo "   docker compose ps | grep chatgpt-agent"
echo "   # Erwartung: Keine Ausgabe"
echo ""
echo "   pm2 status | grep reading-agent"
echo "   # Erwartung: reading-agent läuft"
echo ""
echo "   curl http://localhost:4000/health"
echo "   # Erwartung: {\"status\":\"ok\"}"
echo ""
echo "CK-App Server:"
echo "   docker compose ps frontend"
echo "   # Erwartung: frontend läuft"
echo ""
echo ""

echo "✅ Deployment-Schritte abgeschlossen!"
echo ""
echo "📋 Nächste Schritte:"
echo "   1. Teste Reading-Generierung über Frontend API"
echo "   2. Prüfe n8n Workflow (falls verwendet)"
echo "   3. Prüfe Logs auf Fehler"
echo ""
